### ISSUE TITLE
Why is web the default process type in procfile?

### ISSUE THREAD

**Issue by jcumminsr1** [jamieforrest/github-asana#10]
I can easily change this in my own instance, but I was wondering if others have done the same . Why is the current default a web process instead of worker? Seems like this is a perfect case for a worker. I am relatively new to heroku so let me know if there is a good design reason to select web over worker.

**Comment by jamieforrest** [comment]
Because the application is a web server, responding to incoming HTTP requests from GitHub hooks.

**Comment by rud** [comment]
This question looks safe to close

**Comment by jamieforrest** [comment]
Thanks @rud
