### ISSUE TITLE
not marking complete -- is this project the default github-asana integration?

### ISSUE THREAD

**Issue by jkeesh** [jamieforrest/github-asana#19]
I've just installed and when I use as directed (commit message iwth "... fixes #12345 ..."
in my webhook dashboard on github it show the message

Last delivery was not successful. An exception occurred. 

It created a new comment in asana, but did mark the task as complete.

**Comment by bendrucker** [comment]
See the lengthy discussion in #14 about this. I believe I fixed everything. Also make sure you're installing from git because the package is way out of sync. 

``` sh
npm install --save jamieforrest/github-asana
```

**Comment by jamieforrest** [comment]
@bendrucker Thanks for the response.
