### ISSUE TITLE
Github webook doesnt respect the verbs for a task

### ISSUE THREAD

**Issue by kylefowler** [jamieforrest/github-asana#25]
In the source it looks like a commit message with something like "fixes #123456" should close the task, but that doesnt actually happen when the github webook is run. It correctly makes the comment on the task but doesnt do anything else. Is the code in this repo actually the one running in the Asana Github webook?

**Comment by gfellerph** [comment]
Noticed this as well.

**Comment by GlennV** [comment]
+1
