### ISSUE TITLE
username is undefined

### ISSUE THREAD

**Issue by rajagopals** [jamieforrest/github-asana#4]
The text of the Asana task comment is "undefined referenced this issue from a commit --------", Essentially the username from github's webhook is turning out to be undefined. Any idea why?

**Comment by jamieforrest** [comment]
Does the commit have an author in github? E.g., this commit: https://github.com/jamieforrest/github-asana/tree/43deb824263070198deb87bbf7bd3b8f1580b815

Look for "jamieforrest" authored a month ago.

Does your commit have similar data on it?

**Comment by rajagopals** [comment]
Yea. It does. Its a private repository though. So can't share the link. It says "Rajagopal Sathyamurthi authored 29 minutes ago" on my commit.

**Comment by rajagopals** [comment]
Ah. I see what you are saying. In mine, "Rajagopal Sathyamurthi" is just a name rather than a link to my homepage. I wonder why... Is it a github setting?

**Comment by jamieforrest** [comment]
Try editing your profile and adding (or changing?) your username.

**Comment by rajagopals** [comment]
Hmm. So my gitconfig file had a different email address than the one I had setup my github account with. I had to change the ~/.gitconfig file to use the same email address. All my new pushes now have the username showing up correctly. Also, it looks like the previous commits will look fine once the cache expires on them. 

Thanks for your time. Closing this issue now.

**Comment by tedostrem** [comment]
I have the same issue. 

~/.bash_profile
export ASANA_USERS='[{"username":"tedostrem", "key":"XXX"}]'

~/.gitconfig
[user]
    name = tedostrem
    email = ted@byteavenue.com

On github account settings I also changed my name to tedostrem

but still
text: 'undefined referenced this issue from a commit' 

Is this project still relevant or is there something new I'm suppose to be using instead?

Thanks

**Comment by jamieforrest** [comment]
Is that email address setup in your GitHub account?

**Comment by tedostrem** [comment]
Yeah it is
