### ISSUE TITLE
A single API key means all comments are from the same person

### ISSUE THREAD

**Issue by orientalperil** [jamieforrest/github-asana#7]
Since only one API key is used, this means that all the comments posted by github-asana will be attributed to the user who owns the API key. In a team of more than one it would be confusing to have the generated comments look like they are all coming from the same person even though the commits are coming from different people.

Does github-asana prefix the generated comments with the name of the committer?
Is there a plan for mapping of committer names to each person's API key?

**Comment by ivanbreet** [comment]
We are currently addressing this by having a separate developer account on Asana (Developer dev@company-name.com), and using that accounts API key for linking them up.

**Comment by jcumminsr1** [comment]
For those interested in having comments from multiple users instead of using a dedicated account. Take a look at @LarsHassler's fork https://github.com/LarsHassler/github-asana
